name: music_player_basic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  audio_video_progress_bar: ^2.0.3
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  just_audio: ^0.9.39
  just_audio_background: ^0.0.1-beta.13
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
